<a href="https://colab.research.google.com/github/Princebhagat001/CM_workshop1.py/blob/main/week6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prince Bhagat

In [1]:
# Problem 1
import numpy as np
if __name__ == "__main__":
  arr = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=float)
  print("Array =")
  print(arr)
  print("Data Type of the Array =", arr.dtype)
  print("Number of dimensions of the Array =", arr.ndim)
  print("Shape of the Array =", arr.shape)
  print("Size of the Array =", arr.size)
  print("Number of bytes used by each element of the Array =", arr.itemsize)
  print("Total bytes used by the Array =", arr.nbytes)
  print("Memory layout information =", arr.flags)

Array =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Data Type of the Array = float64
Number of dimensions of the Array = 2
Shape of the Array = (3, 3)
Size of the Array = 9
Number of bytes used by each element of the Array = 8
Total bytes used by the Array = 72
Memory layout information =   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [2]:
# Problem 2
arr2 = 3 * np.ones((4,5), dtype=float)
print("Array = ")
print(arr2)
print("Shape = ",arr2.shape)
print("DataType = ",arr2.dtype)


Array = 
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape =  (4, 5)
DataType =  float64


In [3]:
# Problem 3
import numpy as np
A = np.full((4,5), 3.0)
print(A)


[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


In [4]:
# Problem 4
import numpy as np
arr4=np.fromfunction(lambda i, j: np.abs(i+1-3*(j+1))/2, (3, 3), dtype=int)
print("Array = ")
print(arr4)
print("Shape =", arr4.shape)
print("DataType = ", arr4.dtype)

Array = 
[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]
Shape = (3, 3)
DataType =  float64


In [5]:
# Problem 5
import numpy as np
A = np.diag([1,2,3,4])
print(A)
print("Shape =", A.shape)
print("DataType = ", A.dtype)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Shape = (4, 4)
DataType =  int64


In [6]:
# Problem 6
import numpy as np
A = np.arange(20).reshape(4,5)
B = A[:3, :3]
print("Original:\n", A)
print("Sliced:\n", B)

Original:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Sliced:
 [[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]


In [7]:
# Problem 1
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
B = np.array([[1,1,1],
              [2,2,2]])
print(A + B)

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [8]:
# Problem 2
import numpy as np
def dot_product(vec1, vec2):
  vec1 = vec1.flatten()
  vec2 = vec2.flatten()
  return np.sum(np.multiply(vec1, vec2))
def matrix_vector_product(mat, vec):
  m,n = mat.shape
  p,q = vec.shape
  assert n == p, "the matrix and vector are not compatible for multiplication!"
  result = np.zeros((m,q), dtype=float)
  for i in range(m):
    result[i] = dot_product(mat[i,:], vec)
  return result
if __name__ == "__main__":
  mat1 = np.full((3,3), 3, dtype=int)
  vec1 = np.full((3,1), 2, dtype=int)
  print("Matrix = ")
  print(mat1)
  print("Vector = ")
  print(vec1)
  result1 = matrix_vector_product(mat1, vec1)
  print("Result = ")
  print(result1)
  result2 = mat1 @ vec1
  print("Result = ")
  print(result2)

Matrix = 
[[3 3 3]
 [3 3 3]
 [3 3 3]]
Vector = 
[[2]
 [2]
 [2]]
Result = 
[[18.]
 [18.]
 [18.]]
Result = 
[[18]
 [18]
 [18]]


In [9]:
# Problem 3
import numpy as np
def mat_mat(A, B):
    result = [[0]*len(B[0]) for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result
A = [[1,2,3],
     [4,5,6],
     [7,8,9]]
x = [[1],[1],[1]]
print(mat_mat(A,x))
A_np = np.array(A)
x_np = np.array(x)
print(A_np @ x_np)

[[6], [15], [24]]
[[ 6]
 [15]
 [24]]


In [11]:
# Problem 4
def is_symmetric(A):
    A = np.array(A)
    return np.array_equal(A, A.T)
A = [[1,2,3],
     [2,5,6],
     [3,6,9]]
print(is_symmetric(A))

True
